[tools]
node = "24"

[tasks.dev]
description = "Start dev environment in docker"
run = "docker compose -f compose-dev.yml up -d --build --remove-orphans"

[tasks.stop]
description = "Stop dev environment and delete all docker volumes"
run = "docker compose -f compose-dev.yml down --volumes"
